baseURL = 'https://new.ruffles.pw/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to my blog!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.portrait]
    path = "/img/me.jpg"
    maxWidth = "220px"

  [[params.social]]
    name = "github"
    url = "https://github.com/pippinmole/"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCROWCHDgV1bgbZvBgKu6yzA"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/pippinmole"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hi, I'm Jonathan 👋"
    subtitle = "This is my portfolio site"
    keywords = "portfolio"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Jonathan Ruffles"
      logoHomeLink = "/" 
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

  [[menu.main]]
    identifier = "Resume"
    name    = "Resume"
    url        = "/cv.pdf"